In [48]:
from pathlib import Path
import numpy as np


def read_sounding(file):

    with open(file) as f:
        lines = f.readlines()

    header = lines[1].split()

    df = pd.read_csv(
        file,
        sep=r"\s*\|\s*",
        engine="python",
        skiprows=3,
        header=None,
        names=header
    )

    return df
df = read_sounding("/users/jdelbeke/soundings/20240101_06610_data.txt")

print(df["termin"].unique())

from scipy.signal import savgol_filter

def detect_inversion(
    df,
    max_height=1000,
    edge_buffer_m=50,
    grid_res=20,
    threshold=0.01,
    min_depth=100
):

    profile = df.loc[df["level"] <= max_height, ["level","745"]]
    profile = profile.dropna(subset=["level", "745"])

    profile = (
        profile.groupby("level", as_index=False)["745"]
        .mean()
        .sort_values("level")
    )

    z = profile["level"].values
    T = profile["745"].values

    if len(z) < 20:
        return np.nan, np.nan

    z_uniform = np.arange(z.min(), z.max(), grid_res)
    T_uniform = np.interp(z_uniform, z, T)


    win = min(21, (len(z_uniform)//2)*2-1)

    if win < 5:
        return np.nan, np.nan


    dTdz = savgol_filter(
        T_uniform,
        window_length=win,
        polyorder=2,
        deriv=1,
        delta=grid_res
    )


    # flip sign if needed
    dTdz = -dTdz


    mask = (
        (z_uniform > z_uniform.min()+edge_buffer_m) &
        (z_uniform < z_uniform.max()-edge_buffer_m)
    )


    candidates = np.where(
        mask & (dTdz > threshold)
    )[0]


    if len(candidates) == 0:
        return 0, np.nan


    # strongest point
    idx = candidates[np.argmax(dTdz[candidates])]


    # check vertical persistence
    above = dTdz > threshold

    levels = z_uniform[above]

    close = levels[
        abs(levels-z_uniform[idx]) < min_depth
    ]

    if len(close) < min_depth/grid_res:
        return 0, np.nan

    return dTdz[idx], z_uniform[idx]

strength, height = detect_inversion(df)

if np.isnan(height):
    print("no clear inversion")
else:
    print(strength, height)

soundings_dir = Path("/users/jdelbeke/soundings")

files = sorted(soundings_dir.glob("*_06610_data.txt"))

results=[]

for file in files:

    df = read_sounding(file)

    for termin, sounding in df.groupby("termin"):

        strength, height = detect_inversion(
            sounding,
            threshold=0.01
        )

        results.append({
            "file": file.name,
            "termin": termin,
            "inversion_strength": strength,
            "inversion_height": height
        })


results=pd.DataFrame(results)

results.head()

[20240101000000 20240101120000]
0.04089866117863829 60.0

,file,termin,inversion_strength,inversion_height
0,20240101_06610_data.txt,20240101000000,0.041718,920.0
1,20240101_06610_data.txt,20240101120000,0.048154,60.0
2,20240102_06610_data.txt,20240102000000,0.036509,700.0
3,20240102_06610_data.txt,20240102120000,0.027147,580.0
4,20240103_06610_data.txt,20240103000000,0.036878,60.0

In [51]:
inv = results.dropna(subset=["inversion_strength"]).copy()

# remove non-events if you used 0 for "no inversion"
inv = inv[inv["inversion_strength"] > 0]

inv.head()

p95 = inv["inversion_strength"].quantile(0.95)

print("95th percentile strength:", p95)

strongest_5pct = inv[
    inv["inversion_strength"] >= p95
].sort_values(
    "inversion_strength",
    ascending=False
)


strongest_5pct_date = strongest_5pct.sort_values(
    "termin",
    ascending=True
)

with pd.option_context("display.max_rows", None):
    display(strongest_5pct_date)

95th percentile strength: 0.05619862128146448

,file,termin,inversion_strength,inversion_height
112,20240223_06610_data.txt,20240223120000,0.063701,60.0
172,20240323_06610_data.txt,20240323120000,0.081057,60.0
190,20240401_06610_data.txt,20240401120000,0.057415,60.0
220,20240416_06610_data.txt,20240416000000,0.068983,920.0
221,20240416_06610_data.txt,20240416120000,0.056960,60.0
229,20240420_06610_data.txt,20240420120000,0.058189,60.0
237,20240424_06610_data.txt,20240424120000,0.073922,60.0
241,20240426_06610_data.txt,20240426120000,0.057720,920.0
285,20240517_06610_data.txt,20240517120000,0.070373,60.0
289,20240519_06610_data.txt,20240519120000,0.056199,60.0
322,20240604_06610_data.txt,20240604150000,0.063632,60.0
331,20240607_06610_data.txt,20240607120000,0.058139,60.0
353,20240613_06610_data.txt,20240613120000,0.069391,60.0
359,20240616_06610_data.txt,20240616120000,0.061918,60.0
380,20240624_06610_data.txt,20240624120000,0.058180,60.0
384,20240626_06610_data.txt,20240626120000,0.059218,60.0
388,20240627_06610_data.txt,20240627120000,0.081580,60.0
400,20240701_06610_data.txt,20240701120000,0.059203,60.0
402,20240702_06610_data.txt,20240702120000,0.078336,60.0
406,20240704_06610_data.txt,20240704120000,0.058166,60.0
422,20240711_06610_data.txt,20240711120000,0.056268,60.0
426,20240713_06610_data.txt,20240713120000,0.072625,60.0
433,20240716_06610_data.txt,20240716120000,0.063828,60.0
435,20240717_06610_data.txt,20240717120000,0.062497,60.0
445,20240722_06610_data.txt,20240722120000,0.057732,60.0
453,20240726_06610_data.txt,20240726120000,0.066915,60.0
483,20240808_06610_data.txt,20240808120000,0.066265,60.0
564,20240912_06610_data.txt,20240912190000,0.061723,920.0
594,20240927_06610_data.txt,20240927120000,0.062289,60.0
605,20241002_06610_data.txt,20241002120000,0.060569,60.0
625,20241011_06610_data.txt,20241011120000,0.059529,60.0
701,20241117_06610_data.txt,20241117120000,0.058070,60.0
708,20241121_06610_data.txt,20241121000000,0.062699,60.0
739,20241206_06610_data.txt,20241206120000,0.067661,60.0
826,20250117_06610_data.txt,20250117120000,0.058398,920.0
959,20250323_06610_data.txt,20250323120000,0.059874,60.0
962,20250324_06610_data.txt,20250324220000,0.060266,920.0
970,20250328_06610_data.txt,20250328120000,0.059000,60.0
978,20250401_06610_data.txt,20250401120000,0.066460,60.0
1012,20250418_06610_data.txt,20250418120000,0.065286,60.0
1052,20250508_06610_data.txt,20250508120000,0.058470,60.0
1071,20250517_06610_data.txt,20250517120000,0.056996,60.0
1073,20250518_06610_data.txt,20250518120000,0.058735,60.0
1085,20250524_06610_data.txt,20250524120000,0.056745,60.0
1087,20250525_06610_data.txt,20250525120000,0.057213,60.0
1095,20250529_06610_data.txt,20250529120000,0.068675,60.0
1130,20250615_06610_data.txt,20250615120000,0.061460,60.0
1132,20250616_06610_data.txt,20250616120000,0.058454,60.0
1134,20250617_06610_data.txt,20250617120000,0.061832,60.0
1148,20250624_06610_data.txt,20250624120000,0.068858,60.0
1155,20250627_06610_data.txt,20250627120000,0.063633,60.0
1177,20250708_06610_data.txt,20250708120000,0.063450,60.0
1181,20250710_06610_data.txt,20250710120000,0.057114,60.0
1183,20250711_06610_data.txt,20250711120000,0.056862,60.0
1185,20250712_06610_data.txt,20250712120000,0.064786,60.0
1189,20250714_06610_data.txt,20250714120000,0.069707,60.0
1191,20250715_06610_data.txt,20250715120000,0.060627,60.0
1193,20250716_06610_data.txt,20250716120000,0.065955,60.0
1195,20250717_06610_data.txt,20250717120000,0.063133,60.0
1205,20250722_06610_data.txt,20250722120000,0.058212,60.0
1207,20250723_06610_data.txt,20250723120000,0.060130,60.0
1209,20250724_06610_data.txt,20250724120000,0.063404,60.0
1221,20250730_06610_data.txt,20250730120000,0.058662,60.0
1257,20250817_06610_data.txt,20250817120000,0.057241,60.0
1271,20250823_06610_data.txt,20250823120000,0.064228,60.0
1321,20250916_06610_data.txt,20250916120000,0.067803,60.0
1326,20250918_06610_data.txt,20250918210000,0.057194,620.0
1340,20250925_06610_data.txt,20250925120000,0.057927,60.0
1362,20251006_06610_data.txt,20251006120000,0.058261,60.0
1398,20251024_06610_data.txt,20251024120000,0.080624,60.0
1521,20251224_06610_data.txt,20251224120000,0.057550,60.0
1539,20260102_06610_data.txt,20260102120000,0.056428,60.0
1579,20260121_06610_data.txt,20260121120000,0.056942,920.0
1706,20260315_06610_data.txt,20260315120000,0.061889,60.0
1744,20260403_06610_data.txt,20260403120000,0.057215,60.0
1748,20260405_06610_data.txt,20260405120000,0.061911,60.0
1770,20260416_06610_data.txt,20260416120000,0.063135,60.0
1780,20260421_06610_data.txt,20260421120000,0.061217,60.0
1790,20260426_06610_data.txt,20260426120000,0.057725,60.0
1822,20260512_06610_data.txt,20260512120000,0.067942,60.0
1824,20260513_06610_data.txt,20260513120000,0.086173,60.0
1832,20260517_06610_data.txt,20260517120000,0.057841,60.0
1860,20260531_06610_data.txt,20260531120000,0.065119,60.0
1862,20260601_06610_data.txt,20260601120000,0.058491,60.0
1872,20260606_06610_data.txt,20260606120000,0.075676,60.0
1873,20260607_06610_data.txt,20260607000000,0.056868,920.0
1874,20260607_06610_data.txt,20260607120000,0.066371,60.0
1882,20260611_06610_data.txt,20260611120000,0.059579,60.0
1890,20260615_06610_data.txt,20260615120000,0.060279,60.0
1913,20260626_06610_data.txt,20260626120000,0.056575,60.0
1915,20260627_06610_data.txt,20260627120000,0.080350,60.0
1917,20260628_06610_data.txt,20260628120000,0.064775,60.0
1923,20260630_06610_data.txt,20260630140000,0.073882,60.0
1924,20260630_06610_data.txt,20260630180000,0.059701,60.0
1932,20260702_06610_data.txt,20260702120000,0.094105,60.0
1934,20260703_06610_data.txt,20260703120000,0.076138,60.0
1936,20260704_06610_data.txt,20260704120000,0.078842,60.0
1940,20260706_06610_data.txt,20260706120000,0.063459,60.0
1952,20260712_06610_data.txt,20260712120000,0.062762,60.0

In [40]:
sounding = df[df["termin"] == df["termin"].unique()[0]]
profile = sounding[sounding["level"] <= 1000].dropna(subset=["level","745"])
profile = profile.groupby("level", as_index=False)["745"].mean().sort_values("level")
print(len(profile))          # is this ~similar across many files? supports the theory
print(profile.head(15))      # check if T looks reasonable near the surface

999
    level    745
0     0.0  20.00
1     1.0  20.84
2     2.0  21.33
3     3.0  21.49
4     4.0  21.51
5     5.0  21.61
6     6.0  21.80
7     7.0  21.87
8     8.0  21.93
9     9.0  22.11
10   10.0  22.15
11   11.0  22.13
12   12.0  22.13
13   13.0  22.12
14   14.0  22.05